// Copyright (c) 2018-present Anbillon Team (anbillonteam@gmail.com).
// Code generated by sqlbrick. DO NOT EDIT IT.

package models

import (
	"github.com/jmoiron/sqlx"
)

// Type definition for SqlBrick. It contains all bricks depends on the number of
// sql files. It alson wrap some sqlx func for for convenience.
type SqlBrick struct {
	Db   *sqlx.DB
	Book *BookBrick
	User *UserBrick
}

// NewSqlBrick create a new SqlBrick to operate all bricks.
func NewSqlBrick(db *sqlx.DB) *SqlBrick {
	return &SqlBrick{
		Db:   db,
		Book: newBookBrick(db),
		User: newUserBrick(db),
	}
}

// Begin wraps the transaction of sqlx.Beginx(). It returns sqlx.Tx to
// operate transaction as sqlx do.
func (s *SqlBrick) Begin() (*sqlx.Tx, error) {
	return s.Db.Beginx()
}
