// {{ .FuncName }} {{ if eq .Comment "" }}generated by sqlbrick, used to operate database table.{{ else }}{{ .Comment }}{{ end }}
func (b *{{ .BrickName }}Brick){{ .FuncName }}() sql.Result {
   return b.db.MustExec(`{{ index .Segments 0 }}`)
}
