// {{ .FuncName }} {{ if eq .Comment "" }}generated by sqlbrick, delete data from database.{{ else }}{{ .Comment }}{{ end }}
func (b *{{ .BrickName }}Brick){{ .FuncName }}({{ .ArgName }} interface{}) (sql.Result, error) {
    {{ $query := index .Segments 0 }}{{ $len := len $query }}{{ if gt $len 40}}stmt, err := b.db.PrepareNamed(
        `{{ $query }}`){{ else }}stmt, err := b.db.PrepareNamed(`{{ $query }}`){{ end }}
    if err != nil {
        return nil, err
    }

    // create map arguments for sqlx
    args := map[string]interface{}{
        {{ range $k, $v := .Args }}"{{ $v }}": {{ $v }},{{ end }}
    }

    return stmt.Exec(args)
}
