// {{ .FuncName }} generated by sqlbrick, delete data from database.
func (b *{{ .BrickName }}Brick){{ .FuncName }}({{ .ArgName }} interface{}) (sql.Result, error) {
    {{ $len := len .Query }}{{ if gt $len 40}}stmt, err := b.db.PrepareNamed(
        `{{ .Query }}`){{ else }}stmt, err := b.db.PrepareNamed(`{{ .Query }}`){{ end }}
    if err != nil {
        return nil, err
    }
    return stmt.Exec({{ .ArgName }})
}
