// {{ .FuncName }} {{ if eq .Comment "" }}generated by sqlbrick, insert data into database.{{ else }}{{ .Comment }}{{ end }}
func (b *{{ .BrickName }}Brick){{ .FuncName }}(args *{{ .BrickName }}) (sql.Result, error) {
    stmt, err := b.db.PrepareNamed(
        `{{ index .Segments 0 }}`)
    if err != nil {
        return nil, err
    }
    return stmt.Exec(args)
}
