// {{ .FuncName }} generated by sqlbrick, insert data into database.
func (b *{{ .BrickName }}Brick){{ .FuncName }}(args *{{ .BrickName }}) (sql.Result, error) {
    stmt, err := b.db.PrepareNamed(
        `{{ .Query }}`)
    if err != nil {
        return nil, err
    }
    return stmt.Exec(args)
}
