// {{ .FuncName }} generated by sqlbrick, select data from database.{{ if gt .TotalArgs 0 }}
func (b *{{ .BrickName }}Brick){{ .FuncName }}(dest interface{}, {{ .ArgName }} interface{}) error {
    stmt, err := b.db.PrepareNamed(
        `{{ .Query }}`)
    if err != nil {
        return err
    }

    rows, err := stmt.Queryx({{ .ArgName }})
    if err != nil {
        return err
    }
    return rows.StructScan(dest)
}
{{ else }}
func (b *{{ .BrickName }}Brick){{ .FuncName }}(dest interface{}) error {
    return b.db.Select(dest, `{{ .Query }}`)
}
{{ end }}