// {{ .FuncName }} generated by sqlbrick, select data from database.{{ if gt .TotalArgs 0 }}
func (b *{{ .BrickName }}Brick){{ .FuncName }}(dest interface{}, {{ .ArgName }} interface{}) error {
    rows, err := b.db.NamedQuery(`{{ .Query }}`, {{ .ArgName }})
    if err != nil {
        return err
    }
    return rows.StructScan(dest)
}
{{ else }}
func (b *{{ .BrickName }}Brick){{ .FuncName }}(dest interface{}) error {
    return b.db.Select(dest, `{{ .Query }}`)
}
{{ end }}