// {{ .FuncName }} generated by sqlbrick, update data in database.
func (b *{{ .BrickName }}Brick){{ .FuncName }}(args *{{ .BrickName }}) (sql.Result, error) {
   return b.db.NamedExec(`{{ .Query }}`, args)
}
