// Code generated by github.com/anbillon/sqlbrick. DO NOT EDIT IT.

// This file is generated from: user.sqb

package entity

// Type definition for User which defined in sqb file.
// This can be used as a model in database operation.
type User struct {
	Id   int32  `db:"id"`
	Name string `db:"name"`
	Age  int32  `db:"age"`
}
